//Esto permite hacer request sin otro programa (get, post, delete, update)
POST https://farmapower-backend-production.up.railway.app/api/users/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "yourPassword123**"
}

###
POST http://localhost:3000/api/requests/vs/visitCandidates
Content-Type: application/json

{
    "idClient": "672b6733dd60abf5b47dd07c",
    "id": "672aca04035a3d6cbf6741e6"
    
}

###
POST http://localhost:3000/api/exchanges/ve/visitExchanges
Content-Type: application/json

{
    "idClient": "672b6733dd60abf5b47dd07c",
    "id": "673fb1a5b7c9819d6f979bf8"
    
}


###
GET http://localhost:3000/api/requests/request/672b6733dd60abf5b47dd07c

###
GET http://localhost:3000/api/requests/x/672b6733dd60abf5b47dd07c

###
GET http://localhost:3000/api/programs

###
GET http://localhost:3000/api/elegiblemedications/

###
POST http://localhost:3000/api/users/signup HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

Esteban
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstLastName"

Pérez
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="secondLastName"

García
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

juan.perez@example.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

SecurePassword123!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

< C:\fakepath\Captura de pantalla 2024-08-13 112524.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
GET http://localhost:3000/api/programs/

###

POST http://localhost:3000/api/exchanges/newExchange HTTP/1.1
Content-Type: application/json

{
    "product": "672aca04035a3d6cbf6741e6",
    "client": "672b6733dd60abf5b47dd07c",
    "pharmacy": "672957359be06fe9f9cf390b",
    "requests": ["672eccd9b82b89340e98246c","672eca82b82b89340e9823ae"]
}

###
GET http://localhost:3000/api/exchanges/all

###
GET http://localhost:3000/api/exchanges/points/672b6733dd60abf5b47dd07c

###
GET http://localhost:3000/api/users/clients