//Esto permite hacer request sin otro programa (get, post, delete, update)
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "yourPassword123**"
}
